Test error in Ruby => C ext support => Ruby
/bin/backtraces:19:in `callback': Ruby callback error (RuntimeError)
	from /lib/truffle/truffle/cext.rb:n:in `rb_funcallv'
	from /src/main/c/cext/call.c:n:in `rb_funcallv'
	from <internal:core> core/truffle/polyglot.rb:148:in `execute'
	from <internal:core> core/truffle/polyglot.rb:148:in `call'
	from /bin/backtraces:23:in `ruby_call'
	from /bin/backtraces:27:in `top'
	from /bin/backtraces:31:in `<main>'

Test with an internal error from rb_mutex_lock()
/lib/truffle/truffle/cext.rb:n:in `lock': deadlock; recursive locking (ThreadError)
	from /lib/truffle/truffle/cext.rb:n:in `rb_mutex_lock'
	from /src/main/c/cext/mutex.c:n:in `rb_mutex_lock'
	from <internal:core> core/truffle/polyglot.rb:148:in `execute'
	from <internal:core> core/truffle/polyglot.rb:148:in `call'
	from /bin/backtraces:45:in `double_lock'
	from /bin/backtraces:49:in `<main>'

Test error in Ruby => C ext => Ruby => C ext Proc => Ruby
/bin/backtraces:59:in `block in bar': error (RuntimeError)
	from /lib/truffle/truffle/cext.rb:n:in `rb_funcall'
	from /ext/backtraces/backtraces.c:5:in `baz'
	from /lib/truffle/truffle/cext.rb:n:in `block in rb_proc_new'
	from /bin/backtraces:59:in `bar'
	from /lib/truffle/truffle/cext.rb:n:in `rb_funcall'
	from /ext/backtraces/backtraces.c:9:in `foo'
	from /lib/truffle/truffle/cext_ruby.rb:n:in `foo'
	from /bin/backtraces:64:in `<main>'

Test error in the callback to the Sulong-instrinsified qsort()
[1, 2, 3, 4]
/bin/backtraces:76:in `block in <main>': error from Ruby called from instrinsified qsort() (RuntimeError)
	from /lib/truffle/truffle/cext.rb:n:in `rb_funcall'
	from /ext/backtraces/backtraces.c:17:in `compare_function'
	from com.oracle.truffle.llvm.libraries.bitcode/src/qsort.c:n:in `sulong_qsort'
	from com.oracle.truffle.llvm.libraries.bitcode/src/qsort.c:n:in `qsort'
	from /ext/backtraces/backtraces.c:25:in `call_qsort'
	from /lib/truffle/truffle/cext_ruby.rb:n:in `qsort'
	from /bin/backtraces:75:in `<main>'

Test error in callback from a native function
42
/bin/backtraces:88:in `error_helper': error from Ruby called from Sulong called from native callback (RuntimeError)
	from /bin/backtraces:93:in `block in <main>'
	from /lib/truffle/truffle/cext.rb:n:in `rb_funcall'
	from /ext/backtraces/backtraces.c:38:in `sulong_callback'
	from /ext/backtraces/backtraces.c:44:in `native_callback'
	from /lib/truffle/truffle/cext_ruby.rb:n:in `native_callback'
	from /bin/backtraces:92:in `<main>'
